import React from "react";
import Head from "next/head";
import Layout from "../../components/Layout/Layout";
import styles from "../../styles/pages/catInfoPage.module.css";

const Cats = (props) => {
  const catInfo = props.post[0];

  return (
    <>
      <Head>
        <title>{catInfo.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devchallenges.png" />
      </Head>

      <Layout>
        <img src={catInfo.image.url} alt={catInfo.name} className={styles.mainCatImage}></img>
      </Layout>
    </>
  );
};

export async function getStaticPaths() {
  const res = await fetch("https://api.thecatapi.com/v1/breeds");
  const cats = await res.json();

  // Get the paths we want to pre-render based on cats
  const paths = cats.map((cat) => ({
    params: { catName: cat.name },
  }));

  // We'll pre-render only these paths at build time.
  // { fallback: false } means other routes should 404.
  return { paths, fallback: false };
}

// This also gets called at build time
export async function getStaticProps(context) {
  const res = await fetch(`https://api.thecatapi.com/v1/breeds`);
  const posts = await res.json();

  const catName = context.params.catName;

  const post = posts.filter((post) => post.name === catName);

  // Pass post data to the page via props
  return { props: { post } };
}

export default Cats;
